"use strict";

// tests for testFunction
// Generated by serverless-mocha-plugin

const mochaPlugin = require("serverless-mocha");
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper("testFunction", "../../../src/functions/testFunction.js", "testFunction");
const AWS = require("aws-sdk-mock");
const AWS_SDK = require("aws-sdk");
AWS.setSDKInstance(AWS_SDK);
describe("testFunction", () => {
  before((done) => {
    done();
  });

  it("implement tests here", async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
